spring:
    # rdb
    datasource:
        url: jdbc:mysql://localhost:3306/sodam?useSSL=false&serverTimezone=Asia/Seoul
        username: root
        password: 12341234
        driver-class-name: com.mysql.cj.jdbc.Driver

    # jpa
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    # redis
    data:
        redis:
            host: localhost
            port: 6379

    # flyway
    flyway:
        locations: classpath:flyway
        baseline-on-migrate: true
        baseline-version: 1
        enabled: true
