spring:
  config:
    import: optional:file:.env[.properties] # .env 활용
  output:
    ansi:
      enabled: always
  application:
    name: sodam-payment
  r2dbc:
    url: r2dbc:mysql://localhost:3306/sodam?ssl=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
  datasource: # flyway를 위해 JDBC 연결 설정
    url: jdbc:mysql://localhost:3306/sodam?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
  flyway: # RDB 형상관리 도구
    locations: classpath:flyway
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8
    check-template-location: true

server:
  shutdown: graceful
  port: 8080
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always

api:
  externalUrl: http://localhost:8081

logging:
  level:
    sodam.backend: debug
    org.springframework.r2dbc.core: debug
    org.springframework.r2dbc.connection.init: debug
    org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler: off
    org.springframework.web.HttpLogging: off
  pattern:
    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%blue(\\(%F:%L\\))|%msg%n"

payment:
  self:
    domain: http://localhost:8080
  toss:
    domain: https://api.tosspayments.com
    key:
      client: ${TOSS_CLIENT_ID}
      secret: ${TOSS_CLIENT_SECRET}

---

spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:pool:h2:mem://localhost/payment
  sql:
    init:
      mode: always
      data-locations: "" # 테스트 환경에서는 더미 데이터 생성 생략
