### create
POST {{domain}}/test-article
Content-Type: application/json

{
  "title": "title from coroutine",
  "body": "body1",
  "authorId": 1234
}

### get
GET {{domain}}/test-article/1
Content-Type: application/json


### get all
GET {{domain}}/test-article/all?title=matched
Content-Type: application/json



### update
PUT {{domain}}/article/1
Content-Type: application/json

{
  "title": "matched title!"
}


### delete
DELETE {{domain}}/article/{{id}}?
    title={{$random.alphanumeric(8)}}
Content-Type: application/json