spring:
  profiles:
    active: local
---
spring:
  output:
    ansi:
      enabled: always
  application:
    name: sodam-webflux-backend
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3308/sample
    username: user
    password: 1234
  sql:
    init:
      mode: always
      schema-locations: classpath:db-init/schema.sql

logging:
  level:
    sodam.backend2: debug
    org.springframework.r2dbc.core: debug
    org.springframework.r2dbc.connection.init: debug
    # 밑에는 스프링 내부적으로 에러가 발생했을 때 해당 클래스 위치에서 로그를 찍음. 하지만, 우리 로깅 형식의 의미를 저해시키므로 꺼주기
    org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler: off
    org.springframework.web.HttpLogging: off
  pattern:
    # console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%logger|%blue(\\(%F:%L\\))|%msg%n" 로깅 형식. 너무길면, logger 제거해서 사용하기
    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%blue(\\(%F:%L\\))|%msg%n" # 시간 - 로그레벨 - MDC에서 세팅한 UUID 형식으로 출력됨
api:
  externalUrl: http://localhost:8081
---
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:pool:h2:file:///./sample
  sql:
    init:
      mode: always
server: # ErrorConfig에서 사용하는 부분
  error:
    include-exception: on
    include-binding-errors: on_param
    include-message: on_param
    include-stacktrace: on_param
---
spring:
  config:
    activate:
      on-profile: stress
  sql:
    init:
      mode: never
logging:
  level:
    sodam.backend2: debug
    org.springframework.r2dbc.core: off
    org.springframework.r2dbc.connection.init: off
---
spring:
  config:
    activate:
      on-profile: prod
server:
  error:
    include-stacktrace: never # 상용 환경에서는 로그 내용 너무 세부적으로 응답하면 보안상 좋지 않음

